import type { ProjectMember } from "./types";

export const projectMembers: ProjectMember[] = [
	{
		id: "elena-feliu",
		name: "Elena Felíu Arquiola",
		imageUrl: "/pics/elena.webp",
		orcidUrl: "https://orcid.org/0000-0002-3711-041X",
		team: "research",
		description: [
			`<p>Elena Felíu Arquiola es Catedrática de Universidad (Área de Lengua Española) en el Departamento de Filología Española de la Universidad de Jaén. Cuenta con cuatro sexenios (el último reconocido en 2022), cinco tramos autonómicos (máximo contemplado por la Junta de Andalucía) y cinco quinquenios de docencia. Es Doctora en Filosofía y Letras (Filología) por la Universidad Autónoma de Madrid (2001), Premio Extraordinario de Licenciatura y Premio Extraordinario de Doctorado. Fue becaria de colaboración del MECD y becaria FPU del MEC. </p>`,
			`<p>Sus líneas de investigación se centran en la gramática del español, especialmente en la morfología y la teoría morfológica, así como en las relaciones de la morfología con la fonología, la sintaxis y la semántica. Destacan sus publicaciones sobre prefijación, sobre relaciones entre morfología y fonología en la creación de acortamientos, sobre construcciones medias y sobre concordancia anómala. Acerca de estos temas ha realizado aportaciones a la sociedad abarcan actividades tanto de transferencia como de divulgación. En cuanto a transferencia, ha colaborado en la revisión de la <i>Nueva gramática de la lengua española</i> de la RAE-ASALE para su segunda edición mediante la elaboración de un informe sobre el capítulo 10, “La prefijación”. En cuanto a su actividad divulgativa relacionada con la gramática del español y con la lingüística, ha escrito artículos en <i>The</i><i> </i><i>Conversation</i> y en <i>Martes Neológico</i> (Centro Virtual Cervantes) y ha participado en la Noche Europea de los Investigadores 2023 y en varias ediciones de la Semana de la Ciencia de la Universidad de Jaén.</p>`,
			`<p>En relación con su trayectoria investigadora, cabe destacar su formación en el extranjero, que se refleja en la realización de varias estancias breves de investigación financiadas en distintos centros: Vrije Universiteit Amsterdam (Países Bajos), University of Essex (Reino Unido) y Université de Montréal (Canadá). Igualmente destaca su capacidad de trabajo en equipo, puesta de manifiesto en su participación como investigadora en once proyectos de investigación nacionales y autonómicos. Finalmente, en cuanto a su capacidad de liderazgo, cabe señalar que actualmente es la investigadora principal del proyecto de investigación <i>Verbos pronominales del español: clasif</i><i>icación y alternancias (VERPRO)</i> (ref. ID2023-149693NB-I00), financiado por el Ministerio de Ciencia, Innovación y Universidades. También ha sido investigadora principal del proyecto de excelencia <i>Problemas de demarcación en morfología y sintaxis: diccionario de unidades y construcciones de</i><i> difícil adscripción en español</i> (ref. HUM673), financiado por la Consejería de Innovación, Ciencia y Empresa de la Junta de Andalucía (2014-2018), así como coordinadora durante cinco años del grupo de investigación <i>A</i><i>nálisis lingüístico</i><i>: teoría y aplicaciones (ALTYA)</i> del Plan Andaluz de Investigación, Desarrollo e Innovación de la Junta de Andalucía (código HUM-834). Junto con David Serrano-Dolader (U. Zaragoza), ha coordinado desde 2012 los <i>Encuentros de </i><i>Morfólogos</i>, que se celebran anualmente en España desde 2005. </p>`,
			`<p>Los resultados de su investigación han visto la luz en editoriales y revistas de prestigio españolas y extranjeras. Es autora de las siguientes monografías: (con Enrique Pato) <i>En torno a la denominada “concordancia adverbial” en español: tres casos de variación</i>, 2022, CSIC, Anejos de la Revista de Filología Española (primer cuartil de las editoriales españolas de SPI) y <i>Morfología derivativa y semántica léxica: la prefijación de auto-, </i><i>co</i><i>- e i</i><i>nter</i>-, 2003,<i> </i>UAM Ediciones (cuarto cuartil de las editoriales españolas de SPI). Igualmente, es autora de numerosos artículos que han sido publicados en revistas como las siguientes: <i>Languages</i> (Q1 en Scimago Journal & Country Rank), <i>Hispania </i>(Q2 en Scimago Journal & Country Rank), <i>Lengua y Habla</i> (Q2 en Scimago Journal & Country Rank), <i>Linguistics</i><i> </i>(Q2 en Scimago Journal & Country Rank), <i>Onomázein</i> (Q2 en Scimago Journal & Country Rank), <i>Revista Signos. Estudios de Lingüística</i><i> </i>(Q2 en Scimago Journal & Country Rank), <i>Zeitschrift</i><i> </i><i>für</i><i> </i><i>romanische</i><i> </i><i>Philologie</i> (Q2 en Scimago Journal & Country Rank),<i> </i><i>Estudios de Lingüística de la Universidad de Alicante</i> <i>(ELUA)</i> (Sello FECYT, cuartil 2) y <i>Verba </i>(Sello FECYT, cuartil 2), entre otras.</p>`,
		],
	},
	{
		id: "carmen-conti",
		name: "Carmen Conti Jiménez",
		imageUrl: "/pics/carmen.webp",
		orcidUrl: "https://orcid.org/0000-0003-3075-3575",
		team: "research",
		description: [
			`<p>Carmen Conti Jiménez es Profesora Titular de Universidad desde 2012 en el Departamento de Filología Española de la Universidad de Jaén y ha sido acreditada para el acceso al cuerpo de Catedrático de Universidad dentro de la Rama de Arte y Humanidades (19-12-2023). Tiene tres sexenios reconocidos (último tramo evaluado activo, 2015-2020), cinco tramos autonómicos (máximo contemplado por la Junta de Andalucía) y cuatro quinquenios de docencia. Es Doctora en Filosofía y Letras (Filología) por la Universidad Autónoma de Madrid, Premio Extraordinario de Licenciatura y Premio Extraordinario de Doctorado. Fue becaria de colaboración del MECD, becaria de FPU del MEC, becaria posdoctoral de la Fundación Caja Madrid, becaria posdoctoral del MEC en EE. UU. y contratada doctora de la Comunidad de Madrid. Ya en su etapa como profesora, obtuvo una beca del Programa José Castillejo para una estancia de investigación de seis meses en UC Berkeley. </p>`,
			`<p>Sus líneas de investigación se centran en el estudio de distintos fenómenos de sintaxis del español, la sintaxis tipológica, la teoría gramatical y la documentación de lenguas amenazadas. Parte de su investigación ha tenido y tiene una vertiente social. Sus labores de documentación lingüística han dado lugar a publicaciones y actividades divulgativas en torno a la defensa y respeto de la diversidad lingüística. También ha trabajado en la creación de materiales didácticos de lenguas amenazadas como el huichol y ha participado en la elaboración de esbozos gramaticales contrastivos orientados a la enseñanza de español a inmigrantes.</p>`,
			`<p>En lo que respecta a su actividad como investigadora, destacan su formación en el extranjero, su capacidad de liderazgo y su trabajo en equipo dentro de proyectos nacionales y autonómicos. Ha realizado estancias de investigación subvencionadas que suman en total más de 24 meses en instituciones internacionales y nacionales de reconocido prestigio en su ámbito, como UC Berkeley, University at Buffalo-SUNY, Rice University-Houston, University of Manchester-Reino Unido, Universidad Nacional Autónoma de México y CSIC-Madrid. En cuanto a su labor de liderazgo, cabe señalar que Carmen Conti ha sido investigadora principal del proyecto <i>Cosubordinación</i><i> en español</i>, del Ministerio de Ciencia e Investigación, y coordinadora en España de una ayuda y dos proyectos de la AECID dentro del Programa de Cooperación Internacional e Investigación Científica. Desde 2021, es coordinadora del Grupo PAIDI de la Junta de Andalucía <i>Análisis Lingüístico: Teoría y Aplicaciones (ALTYA)</i> (HUM-834). En cuanto a su trabajo en equipo, ha sido miembro de distintos proyectos nacionales y autonómicos, y ha colaborado también en proyectos en el extranjero. Actualmente, es miembro del equipo de investigación del proyecto <i>Verbos pronominales del español: clasificación y alternancias</i>, del Ministerio de Ciencia, Innovación y Universidades, dirigido por E. Felíu. </p>`,
			`<p>Los resultados de su investigación han aparecido publicados en español y en inglés en editoriales y revistas de prestigio y se han difundido, también en ambas lenguas, en congresos nacionales e internacionales (dentro y fuera de España). Es autora de cuatro monografías, entre las que destacan especialmente dos: <i>Complejidad lingüística. Orígenes y revisión crítica del concepto de lengua compleja</i>, 2018, Peter Lang (que se encuentra en el primer cuartil de las editoriales extranjeras de SPI, 2018) y <i>Fundamentos de sintaxis tipológica</i>, 2016, Síntesis (que se encuentra en el primer cuartil de las editoriales nacionales de SPI, 2018). Asimismo, es autora de artículos en revistas nacionales e internacionales de reconocido prestigio en su materia, como <i>Studia</i><i> </i><i>Lingüistica</i> (Q1 en Scimago Journal & Country Rank),<i> </i><i>Onomázein</i> (Q2 en Scimago Journal & Country Rank), <i>Folia </i><i>Linguistica</i> (Q2 en Scimago Journal & Country Rank), <i>Zeitschrift</i><i> </i><i>fur</i><i> </i><i>Romanische</i><i> </i><i>Philologie</i> (Q2 en Scimago Journal & Country Rank), <i>Linguistics</i> (Q2 en Scimago Journal & Country Rank), <i>Estudios de Lingüística de la Universidad de Alicante (ELUA)</i> (Sello de la FECYT, cuartil 2) y <i>Verba </i>(Sello de la FECYT, cuartil 2).</p>`,
		],
	},
	{
		id: "ventura-salazar",
		name: "Ventura Salazar García",
		imageUrl: "/pics/ventura.webp",
		orcidUrl: "https://orcid.org/0000-0002-9988-0647",
		team: "research",
		description: [
			`<p>	Nacido en Baeza (1965), se licencia en Filología Hispánica por la Universidad de Granada en 1988. Obtuvo el Doctorado por dicha Universidad en 1995.</p>`,
			`<p>Entre 1988 y 1990 fue profesor de español como lengua extranjera en el Centro de Lenguas Modernas de la Universidad de Granada. A partir de 1990 ha sido profesor de Lingüística General en varias universidades españolas. Primeramente, como profesor asociado, en las Universidades de Granada (1990-1993) y Almería (1993-1998). Posteriormente, ya como profesor titular, en las de Alicante (1998-2005) y Jaén (desde 2005 y en la actualidad), donde ha dirigido hasta el momento nueve Tesis Doctorales. Entre 2016 y 2022 fue Presidente de la Comisión Académica del Programa de Doctorado en Lenguas y Culturas, impartido conjuntamente por las Universidades de Córdoba, Extremadura, Huelva y Jaén. Actualmente es coordinador de la colección <i>Lingüística</i> de la Editorial de la Universidad de Jaén (UJA Editorial). Asimismo, imparte regularmente docencia reglada en la Universidad Internacional “Menéndez Pelayo” y en la Universidad del Sarre (<i>Universität des Saarlandes</i>) en Saarbrücken (Alemania). A eso se añade su colaboración con la Fundación CNSE y con el Centro de Normalización de la Lengua de Signos Española, dependiente del Real Patronato sobre Discapacidad, de la que emana su participación acreditada en la redacción de la <i>Propuesta curricular de la Lengua de Signos Española</i> (niveles A1-A2 y nivel B1) y en la del <i>II Informe</i><i> sobre la situación de la Lengua de Signos Española</i>. Asimismo, en 2019 emitió informes para la Escuela de Doctorado de la Universidad Complutense de Madrid, en calidad de experto.</p>`,
			`<p>Cuenta actualmente con cinco sexenios de investigación, que abarcan ininterrumpidamente el período comprendido entre 1991 y 2020, ambos inclusive. Su investigación atiende diversas cuestiones de lingüística teórica, historiografía y lingüística aplicada, siempre desde una concepción funcional de los hechos del lenguaje. Ha participado en varios proyectos de investigación y colabora regularmente en la edición de varias revistas académicas. Entre 2011 y 2015 fue vocal de la junta directiva de la Sociedad Española de Lingüística. Ha impartido gran número de conferencias y cursos de formación tanto en España como en el extranjero. Asimismo, ha llevado a cabo estancias de investigación en instituciones tales como la Universidad de Ámsterdam, la Pontificia Universidad Gregoriana de Roma y la Universidad de Harvard, entre otras.</p>`,
			`<p>Es autor de más de un centenar de publicaciones académicas, entre las que figuran artículos publicados en revistas como <i>Studies in Language</i>, <i>Open Linguistics</i>, <i>Sign Systems Studies</i>, <i>Estudios de Lingüística</i>, <i>Círculo de Lingüística Aplicada a la Comunicación</i>, <i>MarcoELE</i>, <i>Itinerarios</i>, etc. Asimismo, cuenta con contribuciones publicadas por numerosas editoriales nacionales e internacionales: Mouton de Gruyter, Peter Lang, John Benjamins, Cambridge Scholars, Axac, Octaedro, Prensas Universitarias de Zaragoza, etc.</p>`,
		],
	},
	// work team
	{
		id: "valeria-belloro",
		name: "Valeria A. Belloro",
		imageUrl: "/pics/valeria.webp",
		orcidUrl: "https://orcid.org/0000-0002-2868-2408",
		team: "work",
		description: [
			`<p>Valeria A. Belloro es Profesora-Investigadora de Tiempo Completo desde 2008 en la Facultad de Lenguas y Letras de la Universidad Autónoma de Querétaro, México. Es miembro desde 2011 del Sistema Nacional de Investigadores de CONAHCYT (2011-2015 Nivel C; 2016-2018 Nivel 1; 2019-2027 Nivel 2). Cuenta desde 2011 con el reconocimiento al Perfil Deseable PRODEP de la Secretaría de Educación Pública. Dirigió de dos proyectos financiados por CONAHCYT-Ciencia Básica: "Investigación comparativa de doblados y dislocaciones en tres dialectos del español" (Periodo 2010-2014, Registro 107135), y "Aspectos de la interfaz sintaxis-pragmática en español y lenguas de México (Periodo 2016-2021, Registro 256785) y ha participado como colaboradora en otros proyectos nacionales e internacionales. Es docente a nivel Licenciatura, Maestría y Doctorado en la Universidad Autónoma de Querétaro. Ha dictado cursos y conferencias en universidades de México, Argentina, Chile, España y EEUU. Es Doctora en Lingüística (PhD) por la University at Buffalo, The State University of New York. Fue becaria del Programa Fulbright y de Fundación Antorchas.  </p>`,
			`<p>Su línea de investigación se centra en el estudio de la Interfaz Sintaxis-Pragmática, particularmente sobre el español, pero también ha colaborado en investigaciones sobre el yaqui, maya yucateco, huichol, guaraní y otras lenguas americanas. Ha difundido su investigación en congresos nacionales e internacionales. Es editora del volumen <i>La Interfaz Sintaxis-Pragmática. Estudios teóricos, descriptivos y experimentales</i> (2019, Berlin, De Gruyter), autora de <i>To</i><i> </i><i>the</i><i> </i><i>Right</i><i> </i><i>of</i><i> </i><i>the</i><i> </i><i>Verb</i><i>: </i><i>An</i><i> </i><i>investigation</i><i> </i><i>of</i><i> </i><i>clitic</i><i> </i><i>doubling</i><i> and </i><i>right</i><i> </i><i>dislocation</i><i> in </i><i>three</i><i> </i><i>Spanish</i><i> </i><i>dialects</i> (2015, UK, Cambridge Scholars Publishing), editora de <i>Estudios sobre la Interfaz Sintaxis-Pragmática en español y lenguas de América </i>(2014, dossier temático de la <i>Revista Signo y Seña</i> 25:1), co-editora de <i>Studies</i><i> in Role and Reference </i><i>Grammar</i> (2009, México, UNAM), co-editora de <i>Representaciones Sociales</i> (2002, Buenos Aires, EUDEBA) co-autora de los libros de texto <i>Lengua y Literatura</i> 1 y 2 (1995, Buenos Aires, Métodos), y cuenta con numerosos artículos en revistas y capítulos de libros entre los que se destacan "La estructura focal de las impersonales reflejas y la noción de 'tópico fantasma'" (<i>Lengua y Habla</i> 28, 2024), "Estructura Argumental Preferida por clases aspectuales de predicados", (con L. Guerrero y J.L. Ramírez Luengo), en Company, Concepción (dir.), <i>Sintaxis Histórica de la Lengua Española, Cuarta Parte: Estructura argumental, estructura informativa y discurso. Tradiciones y soportes textuales</i>, México, UNAM/ Fondo de Cultura Económica, 4760pp, en prensa), "Motivaciones para la posición variable del sujeto en guaraní paraguayo", (con M. Califa, <i>LIAMES</i> 24, 1-19, 2024); "Entre pasivas e impersonales: las cláusulas con -wa en yaqui", (con L. Guerrero, <i>RASAL Lingüística</i> 2024(1), 97-118); "Había una vez una construcción presentativa. Funciones discursivas de las oraciones con 'haber' impersonal", (con G. Galindo, <i>Gragoatá</i> v.27 n.58, número especial <i>Língua</i><i>, Gramática e Discurso </i><i>na</i><i> interface pragmática-</i><i>sintaxe</i>, editado por Paulo Pinheiro y Manuel Leonetti, pp.180-208, 2022); "Poniendo el 'foco' en la pasiva perifrástica. Estructura informativa en las oraciones pasivas del español" (<i>Onomázein</i> ​48, pp. 107-127, 2020). </p>`,
		],
	},
	{
		id: "lilian-guerrero",
		name: "Lilián Guerrero",
		imageUrl: "/pics/lilian.webp",
		orcidUrl: "https://orcid.org/0000-0002-6118-913X",
		team: "work",
		description: [
			`<p>Lilián Guerrero es doctora en Lingüística por la Universidad de Búfalo (Estados Unidos) y desde el 2006 es investigadora titular de tiempo completo en el Seminario de Lenguas Indígenas, en el Instituto de Investigaciones Filológicas de la Universidad Nacional Autónoma de México. Forma parte del Sistema Nacional de Investigadores de México (máximo nivel contemplado). En 2024 recibió el Premio Nacional Wigberto Jiménez Moreno del INAH a la mejor investigación en el área de lingüística.</p>`,
			`<p>La línea de investigación que define sus actividades académicas gira en torno a la descripción, documentación y tipología lingüística, así como el estudio de las lenguas indígenas mexicanas. Entre sus áreas de interés destacan el estudio de la interfaz sintaxis-semántica y los efectos pragmáticos en la selección de estructuras alternativas en oraciones simples y complejas; procesos de cambios de valencia, transitividad, y propiedades aspectuales de los predicados; la interfaz sintaxis-semántica y los efectos pragmáticos en la selección de estructuras. Su investigación se adscribe a la sintaxis funcional y descriptiva y, en particular, a los principios de la Gramática de Rol y Referencia. Ha realizado trabajo de campo en la lengua pima (Pilares, Sonora, 1995), yaqui (Estación Vícam, Sonora, desde 1996) y huichol (variantes de Jalisco y Nayarit, desde agosto 2008). Ha sido responsable y corresponsable de 7 proyectos de investigación con financiamiento, todos orientados al estudio de lenguas minoritarias habladas en México. Ha publicado una decena de libros y más de cincuenta capítulos de libros en editoriales de prestigio (entre ellas, Cambridge University Press, Mouton de Gruyter, Oxford University Press, John Benjamins, Language Science Press, entre otras); cuenta con una veintena de artículos de investigación en revistas de alto impacto y especializadas (International Journal of American Linguistics, Folia Lingüística, Onomázein, Liames, entre otras). Sus últimas dos publicaciones corresponden a los libros de autoría <i>Gramática de la locación y el tiempo en yaqui</i>  (2023) y <i>Transitividad (no) canónica</i>. <i>Reflexiones a partir de lenguas habladas en México</i>, junto con Sergio Ibáñez y Yulma Mejía. Breviarios de Lingüística 1. México: UNAM, Posgrado de Lingüística</p>`,
			`<p>En docencia,  ha impartido cursos a nivel licenciatura y posgrado en la Universidad de Sonora, la Universidad Autónoma de Querétaro, la Escuela Nacional de Antropología e Historia (ENAH), el Centro de Investigaciones y Estudios en Antropología Social (CIESAS) y en la Universidad de Jaén (España). Ha dirigido varias tesis de licenciatura, maestría y doctorado en las líneas de investigación que definen su trabajo.</p>`,
		],
	},

	{
		id: "rolf-kailuweit",
		name: "Rolf Kailuweit",
		imageUrl: "/pics/rolf.webp",
		orcidUrl: "https://orcid.org/0000-0002-8795-2121",
		team: "work",
		description: [
			"<p>Rolf Kailuweit es catedrático de Lingüística Románica (español y francés) en la Heinrich Heine Universität de Düsseldorf (Alemania) desde el semestre de invierno 2017/18. Anteriormente, ocupó la cátedra de Lingüística Románica y Estudios de los Medios de Comunicación en la Universidad de Friburgo (Alemania) desde 2004. Tras estudiar lenguas y literaturas románicas, filosofía y derecho en la Universidad Libre de Berlín y en la Universidad de Barcelona, se doctoró en Berlín en 1996 con una tesis sobre el conflicto lingüístico entre castellano y catalán en los siglos XVIII y XIX. Consiguió su habilitación en Heidelberg en 2003 con un estudio sobre el enlace de los verbos de emoción franceses e italianos.</p>",
			"<p>Sus intereses de investigación se centran, por un lado, en la lingüística sistemática, concretamente en la interfaz entre sintaxis y semántica. Por otro lado, se inscriben en el ámbito de los estudios culturales y mediáticos y se refieren al análisis del discurso político y la lingüística de las migraciones, así como a la función de las lenguas regionales y minoritarias. Desde mayo de 2023 es portavoz del paquete de trabajo 2 del proyecto Horizonte UE «Análisis y respuestas a las narrativas extremistas» (ARENAS).</p>",
			`<p>Es autor de trabajos académicos escritos en inglés, alemán, español, francés, catalán, italiano y portugués, entre los que cabe destacar las monografías <i>Vom EIGENEN SPRECHEN – eine Geschichte der spanisch-katalanischen Diglossie in Katalonien (1759-1859)</i> (1997, Frankfurt/Main, Lang) y <i>Linking: Syntax und Semantik französischer und italienischer Gefühlsverben</i> (2003, Tübingen, Niemeyer). Entre sus ensayos recientes figuran los siguientes “Semantic Macroroles” (en Delia Bentley et al., eds.: <i>The Cambridge Handbook of Role and Reference Grammar</i>,<i> </i>Cambridge University Press, 2023, pp. 242-268), “Vengeance” (en Nolwenn Lorenzi Bailly y Claudine Moïse, eds., <i>Discours de haine et de radicalisation: Les notions </i>clés, Lyon, ENS Éditions, 2023, pp. 193-200); “Procesos migratorios entre Europa y América posteriores a la conquista y sus efectos lingüísticos (siglos XVIII, XIX)” (en Eva Martha Eckkrammer, ed.:<i> Manual del español en América</i>, Berlin/Boston, De Gruyter, 2021, pp. 339-358); “Cosubordinación en perífrasis fasales en español, italiano y francés"(en Carmen Conti Jiménez, ed.: <i>Cosubordinación en español, </i>Bern, Peter Lang, 2021, pp. 101-132); "Linguistic landscapes and regional languages in Southern France – a neo-semiotic approach to placemaking conflicts" (en Mónica Castillo Lluch, Rolf Kailuweit y Claus Pusch, eds.: <i>Linguistic Landscape Studies. The French Connection</i >, Freiburg, Rombach 2019, pp. 131 - 162).</p>`,
			"<p>Ha realizado estancias de investigación en la Universidad de Barcelona, en la Universidad de Buenos Aires, en la Universidad Autónoma de Querétaro y en la Universidad Nacional Autónoma de México. Ha sido conferenciante invitado en diversas universidades de Alemania, Suiza, Francia, España, Argentina, México y Chile.</p>",
			"<p>Orcid: https://orcid.org/0000-0002-8795-2121</p>",
		],
	},
	{
		id: "enrique-pato",
		name: "Enrique Pato",
		imageUrl: "/pics/enrique.webp",
		orcidUrl: "https://orcid.org/0000-0002-6955-2861",
		team: "work",
		description: [
			`<p>Enrique Pato es Catedrático de Universidad en el <i>Département de </i><i>littératures et de langues du monde</i> de la <i>Université de Montré</i><i>al</i> (Quebec, Canadá). Doctor en Filología española por la Universidad Autónoma de Madrid (2003), fue becario posdoctoral del Ministerio de Ciencia y Tecnología en la <i>Western University</i> (Ontario, Canadá).</p>`,
			`<p>Sus líneas de investigación se centran en el estudio de la sintaxis dialectal del español, así como en la gramática histórica. Parte de su investigación tiene una vertiente social. También ha trabajado en la revisión y creación de materiales didácticos para la enseñanza del español.</p>`,
			`<p>En lo que respecta a su actividad investigadora, ha sido investigador principal en tres proyectos subvencionados por el <i>Conseil de recherches en sciences humaines</i> de Canadá y los <i>Fonds de recherche sur la société et la culture</i> de Quebec. En cuanto a su trabajo en equipo, ha sido miembro de numerosos proyectos internacionales. Actualmente, es miembro del equipo de investigación de cinco proyectos, incluido <i>Verbos pronominales del español: clasificación y alternancias</i> (Ministerio de Ciencia, Innovación y Universidades).</p>`,
			`<p>Su investigación ha sido publicada en varias editoriales y en más de 70 revistas. Es autor de varias monografías, como <i>En torno a la denominada “concordancia adverbial” en español: tres casos de variación</i> (CSIC, 2020, junto a E. Felíu Arquiola) y es editor de volúmenes colectivos, entre los que destacan <i>Studies in Historical Ibero-Romance Morpho-Syntax</i> (John Benjamins, 2018, con M. Bouzouita y I. Sitaridou), <i>Universales vernáculos en la gramática del español</i> (Iberoamericana/Vervuert, 2022, con Á. di Tulio), <i>Estudios sobre el español de Venezuela</i> (Iberoamericana/Vervuert, 2023) y <i>New Approaches to Spanish Dialectal Grammar</i> (<i>Languages</i>, 2024). Asimismo, es autor de más de un centenar de artículos publicados en revistas nacionales (<i>Estudios de Lingüística de</i><i> la Universidad de Alicante</i>, <i>Verba</i>,<i> </i><i>Moenia</i>,<i> </i><i>Dicenda</i>, <i>Ogigia</i>, <i>Revista de Filología Española</i>, <i>Revista Española de Lingüística</i>, <i>Isogloss</i>, <i>Philologica Canariensia</i>, <i>Archivo de Filología Aragonesa</i>, <i>Boletín de la Real Academia Española</i>, etc.) e internacionales<i> </i>(<i>Onomázein</i>, <i>Zeitschrift </i><i>für</i><i> Romanische Philologie</i>,<i> Languages, Revue de linguistique romane, </i><i>Études romanes de Brno</i>, <i>Iberoromania</i>, <i>Bulletin of Spanish Studies</i>, <i>Canadian Journal of Linguistics</i>, <i>Nueva Revista de Filología Hispánica</i>, <i>Revista Internacional de Lingüística Iberoamericana</i>, <i>Borealis</i>, etc.). Sus trabajos también se han difundido ampliamente en congresos nacionales e internacionales (Canadá, Estados Unidos, México, Guatemala, Honduras, Puerto Rico, Cuba, Argentina, Uruguay, Brasil, Portugal, Alemania, Francia, Bélgica, Suiza, Países Bajos, Austria, Reino Unido, China y Japón).</p>`,
		],
	},

	{
		id: "sergio-ibanez",
		name: "Sergio Ibáñez Cerda",
		imageUrl: "/pics/sergio.webp",
		orcidUrl: "https://orcid.org/0000-0003-3235-5597",
		team: "work",
		description: [
			`<p>El Dr. Sergio Ibáñez Cerda es Doctor en Lingüística (2004) y Maestro en Letras, con especialidad en Lingüística Hispánica (2000) por la Facultad de Filosofía y Letras de la UNAM. Cursó la licenciatura en Ciencias de la Comunicación (1993) en la Facultad de Ciencias Políticas y Sociales de la misma Universidad. Obtuvo mención Honorífica en los tres niveles y recibió sendas medallas Alfonso Caso al Mérito Universitario por sus estudios de maestría y doctorado. Actualmente, el Dr. Ibáñez es investigador ordinario de carrera, Titular “C”, de Tiempo Completo Definitivo, adscrito al Centro de Lingüística Hispánica “Juan M. Lope Blanch.</p>`,
			`<p>Sus principales áreas de investigación son las de la interfaz semántica-sintaxis, la estructura argumental verbal, la semántica léxica y la Gramática del Rol y la Referencia (RRG). Entre sus investigaciones principales destacan: “Adposition assignment and Adpositional phrase types in RRG”, en <i>Handbook of Role and Reference Grammar</i><i> </i>(2023); “Applicative periphrastic constructions in the Colombian Spanish from The Andes”, en <i>Applicative morphology. Neglected syntactic and non-syntactic functions</i> (2022); “Commercial event verbs in Spanish. A corpus-based study”, en <i>Applying and Expanding Role and Reference </i>Grammar, (2018); “PP types in RRG. A top-down approach to their classification”, en <i>New perspectives in </i><i>Role and Reference Grammar</i> (2011); y “Saying verbs. Deepening the lexical semantics description” en <i>Investigations on the Syntax-Semanti</i><i>cs-Pragmatics </i><i>Interface</i> (2008). Destacan también un libro de autoría sobre verbos de movimiento intransitivos del español (2005), un libro coeditado sobre la RRG (2009) y el libro de texto <i>Transitividad (no) canónica: reflexiones a partir de lenguas habladas en México</i> (2022), en coautoría con Lilián Guerrero y Yulma Mejía. </p>`,
			`<p>Es profesor del Programa de Maestría y Doctorado en Lingüística de la UNAM desde el 2004, donde ha impartido los cursos obligatorios de “Sintaxis” y “Semántica” para la Maestrías de Lingüística Hispánica. También ha impartido los cursos optativos de “Semántica y gramáticas léxicas” e “Introducción a la Gramática del Rol y la Referencia”. También, ha sido profesor de la carrera de Lengua y Literaturas Hispánicas de la Facultad de Filosofía y Letras desde el 2001 a la fecha. Ha sido director de 29 tesis terminadas (2 de doctorado, 13 de maestría y 14 de licenciatura) </p>`,
			`<p>Ha sido director de la revista <i>Estudios de Lingüística Aplicada</i> (ELA), publicada por la ENALLT-UNAM (2013-2018). Entre sus actividades académico-administrativas destacan el haber sido Coordinador del Centro de Lingüística Hispánica “Juan M. Lope Blanch”, del Instituto de Investigaciones Filológicas de la UNAM (2016-2020), y el haber sido Coordinador del Programa de Maestría y Doctorado en Lingüística de la misma Casa de Estudios (2008-2011). Actualmente funge como Secretario Académico del Instituto de Investigaciones Filológicas.</p>`,
			`<p>Entre los premios y distinciones que ha recibido el Dr. Ibáñez, destacan el Premio a la “Mejor ponencia de jóvenes investigadores” del XIV Congreso Internacional de la Asociación de Lingüística y Filología de América Latina (2005), el premio Wigberto Jiménez a la mejor tesis de maestría en lingüística (2000), que otorga el Conaculta-INAH y las dos medallas Alfonso Caso como mejor estudiante de maestría (2000) y de doctorado (2004), de las generaciones respectivas.</p>`,
		],
	},
];
